---
- name: Converge
  hosts: all

  roles:
    - role: ../../../lfkdev.camino_node

  post_tasks:
    - name: Check if camino_node service is active
      ansible.builtin.systemd:
        name: camino_node.service
        state: started

    - name: Check camino_node service status
      command: systemctl status camino_node
      register: camino_status

    - debug:
        var: camino_status.stdout
